# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: Name of the new tag
        message:
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Git setup
        run: "git config --local user.email ghaction_release.satqe.com && git config --local user.name ghaction_release"

      - name: add a new tag
        run: "git tag -a ${{ github.event.inputs.tag_name }} -m 'Tagged By SatelliteQE Automation User'"

      - name: push the commit with the tag
        run: "git push ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git --tags"

      - name: print the resulting URL
        run: "echo ${GITHUB_API_URL}/${GITHUB_REPOSITORY}/releases"

      - name: create a release
        env:
          credentials: ${{ secrets.GH_TOKEN }}
        run: "curl -L -X POST -H \"Authorization: Bearer ${{ secrets.GH_TOKEN }}\" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases -d '{\"draft\":false, \"prerelease\":true, \"generate_release_notes\": true, \"tag_name\": \"${{ github.event.inputs.tag_name }}\", \"target_commitish\": \"${GITHUB_REF_NAME}\"}'"
